presubmits:
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.9
          command:
            - "pre-commit"
            - "run"
            - "--all-files"

postsubmits:
  - name: peribolos
    decorate: true
    run_if_changed: "community/github-config.yaml"
    skip_report: false
    context: community-management/prow/peribolos
    branches:
      - master
    spec:
      containers:
        - image: gcr.io/k8s-prow/peribolos:latest
          command:
            - /bin/sh
          args:
            - -c
            - |
              set -ex
              /peribolos --config-path community/github-config.yaml --github-token-path /etc/github/oauth --fix-org --confirm
          volumeMounts:
            - name: github-oauth
              mountPath: /etc/github
      volumes:
        - name: github-oauth
          secret:
            secretName: oauth-token
