---
  - name: "make sure to use project {{ THOTH_MIDDLETIER_NAMESPACE }}"
    command: "oc project {{ THOTH_MIDDLETIER_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: deploy Thoth Result API
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/result-api-deployment"

  - name: deploy JanusGraph Database
    command: "oc new-app --template={{ THOTH_INFRA_NAMESPACE }}/janusgraph"
    ignore_errors: true

  - name: create Thoth Job templates
    command: oc create --save-config=true --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/package-extract/master/openshift/job-template.yaml
      - https://raw.githubusercontent.com/thoth-station/solver/master/openshift/job-template.yaml

  - name: create Thoth Package Extract ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-extract-imagestream"

  - name: create Thoth Solver ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/solver-imagestream"

  - name: create Thoth Dependency Monkey Job template
    command: oc create --save-config=true --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/job-dependencyMonkey-template.yaml
