---
  - name: login to OpenShift using provided token
    command: "oc login --insecure-skip-tls-verify=true --token {{ token }} {{ openshift_master_url }}"

  - name: "create Thoth Tiers"
    command: "oc new-project {{ item }}"
    ignore_errors: true
    with_items:
      - "{{ THOTH_BACKEND_NAMESPACE  }}"
      - "{{ THOTH_MIDDLETIER_NAMESPACE }}"
      - "{{ THOTH_FRONTEND_NAMESPACE }}"
      - "{{ THOTH_INFRA_NAMESPACE }}"

  - name: "make sure to use project {{ THOTH_INFRA_NAMESPACE }}"
    command: "oc project {{ THOTH_INFRA_NAMESPACE }}"
    register: project_exists
    ignore_errors: true

  - name: create Thoth Core template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/template.yaml
    register: template_rc

  - name: create Thoth User API templates
    command: "oc create --namespace {{ THOTH_INFRA_NAMESPACE }} --filename {{ item }}"
    register: template_rc
    with_items:
      - "https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/deployment-template.yaml"
      - "https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/buildConfig-template.yaml"

  - name: create Thoth Result API templates
    command: "oc create --namespace {{ THOTH_INFRA_NAMESPACE }} --filename {{ item }}"
    register: template_rc
    with_items:
      - "https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/deployment-template.yaml"
      - "https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/buildConfig-template.yaml"

  - name: create Thoth Core secrets template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/secret-template.yaml

  - name: create Thoth Core configmap template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/configmap-template.yaml
 
  - name: create Thoth Package Releases CronJob template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/cronJob-template.yaml
 
  - name: create Thoth Package Releases BuildConfig template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/buildConfig-template.yaml

  - name: create JanusGraph Database Template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE }}" \
        --filename https://raw.githubusercontent.com/goern/janusgraph-openshift/master/template.yaml