---
  - name: "make sure to use project {{ THOTH_BACKEND_NAMESPACE }}"
    command: "oc project {{ THOTH_BACKEND_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: create Thoth Adviser Job template
    command: oc create --save-config=true --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/job-adviser-template.yaml

  - name: create Thoth Provenance Checker Job template
    command: oc create --save-config=true --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/job-provenanceChecker-template.yaml

  - name: create Thoth Adviser ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/adviser-imagestream"
