# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
heart:
  adorees:
  - sesheta

approve:
- repos:
  - goern/bots-playground
  - thoth-station/core
  - thoth-station/user-api
  - thoth-station/result-api
  - thoth-station/common
  - thoth-station/storages
  - thoth-station/analyzer
  - thoth-station/adviser
  - thoth-station/solver
  - thoth-station/package-extract
  - thoth-station/cleanup-job
  - thoth-station/graph-refresh-job
  - thoth-station/package-releases-job
  - thoth-station/graph-sync-job
  - thoth-station/dependency-monkey
  - thoth-station/build-analysers
  - thoth-station/jupyter-notebook
  - thoth-station/notebooks
  - thoth-station/lab
  - thoth-station/naming-service
  - thoth-station/misc
plugins:
  goern/bots-playground:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart

  thoth-station/core:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/user-api:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/result-api:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size

  thoth-station/common:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size

  thoth-station/storages:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/analyzer:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/adviser:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/solver:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/package-extract:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/cleanup-job:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/graph-refresh-job:
    - approve
    - label
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/package-releases-job:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/graph-sync-job:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/dependency-monkey:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/build-analysers:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/jupyter-notebook:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/notebooks:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/lab:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/naming-service:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart
  thoth-station/misc:
    - approve
    - assign
    - lgtm
    - wip
    - hold
    - lifecycle
    - size
    - heart