---
  - name: "make sure to use project {{ THOTH_FRONTEND_NAMESPACE }}"
    command: "oc project {{ THOTH_FRONTEND_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: deploy Thoth Core
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLETIER_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}"

  - name: deploy Thoth User API
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/user-api-deployment" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}"

  - name: create Thoth Package Releases CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-cronjob" \
        -p THOTH_SUSPEND_JOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Package Releases ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-imagestream"

  - name: create Thoth Graph Sync CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-cronjob" \
        -p THOTH_SUSPEND_JOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Graph Sync ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-imagestream"

  - name: create Thoth Graph Refresh CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-cronjob" \
        -p THOTH_SUSPEND_JOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Graph Refresh ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-imagestream"

  - name: create Thoth Cleanup CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-cronjob" \
        -p THOTH_SUSPEND_JOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Cleanup ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-imagestream"

  - name: create Thoth CVE Update ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cve-update-imagestream"

  - name: create Thoth CVE Update CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cve-update-cronjob" \
        -p THOTH_SUSPEND_JOB="{{ THOTH_SUSPEND_CRONJOBS }}"
