apiVersion: v1
kind: Pod
metadata:
  name: manual-graph-sync-batchjob
  labels:
    app: thoth-core
    ops-mode: manual
spec:
  containers:
  - name: graph-sync-batchjob
    image: graph-sync-cronjob
    env:
    - name: THOTH_DEPLOYMENT_NAME
      valueFrom:
        configMapKeyRef:
          key: storage-bucket-name
          name: thoth
    - name: THOTH_JANUSGRAPH_HOST
      value: janusgraph
    - name: THOTH_JANUSGRAPH_PORT
      value: '80'
    - name: THOTH_GRAPH_SYNC_DEBUG
      value: '1'
    - name: THOTH_LOG_STORAGES
      value: 'DEBUG'
    - name: THOTH_SYNC_OBSERVATIONS
      valueFrom:
        configMapKeyRef:
          key: sync-observations
          name: thoth
    - name: THOTH_CEPH_HOST
      valueFrom:
        configMapKeyRef:
          key: ceph-host
          name: thoth
    - name: THOTH_CEPH_BUCKET
      valueFrom:
        configMapKeyRef:
          key: ceph-bucket-name
          name: thoth
    - name: THOTH_CEPH_BUCKET_PREFIX
      valueFrom:
        configMapKeyRef:
          key: ceph-bucket-prefix
          name: thoth
    - name: THOTH_CEPH_KEY_ID
      valueFrom:
        secretKeyRef:
          name: thoth
          key: ceph-key-id
    - name: THOTH_CEPH_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: thoth
          key: ceph-secret-key
    resources:
      requests:
        memory: "128Mi"
        cpu: "125m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  restartPolicy: Never