apiVersion: v1
kind: Template
metadata:
  name: thoth-core-secret
  annotations:
    description: >
      This is Thoth Secrets - All the secrets required to deploy Thoth Core Analyzer and Results API 
    openshift.io/display-name: Thoth Core Secrets
    version: 0.4.0
    tags: poc,thoth,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: >
      This template defines secrets required to deploy Thoth Core Services to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: thoth
    template: thoth-core-secret
    component: secret

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: thoth
    labels:
      app: thoth
      component: secret
  stringData:
    app-secret-key: ${THOTH_APP_SECRET_KEY}
    thoth-secret: ${THOTH_SECRET}
    ceph-key-id: ${THOTH_CEPH_KEY_ID}
    ceph-secret-key: ${THOTH_CEPH_SECRET_KEY}
    sentry-dsn: ${SENTRY_DSN}

parameters:
  - description: Secret key for flask application to have secure sessions connection.
    displayName: App secret key
    required: true
    name: THOTH_APP_SECRET_KEY

  - description: Secret to interact with Thoth endpoints that require higher privileges.
    displayName: Thoth secret
    required: true
    name: THOTH_SECRET

  - description: Access key id for Ceph connection.
    displayName: Ceph access key id
    required: true
    name: THOTH_CEPH_KEY_ID

  - description: Secret key for Ceph connection.
    displayName: Ceph secret key
    required: true
    name: THOTH_CEPH_SECRET_KEY

  - displayName: SENTRY_DSN
    description: A DSN to a Sentry instance to log to.
    name: SENTRY_DSN
    required: false