apiVersion: v1
kind: Template
labels:
  template: thoth-core-secret
  thoth: 0.1.0
metadata:
  name: thoth-core-secret
  annotations:
    description: This is Thoth Core Secrets - All the secrets required to deploy Thoth Core Analyzer and Results API 
    openshift.io/display-name: Thoth Core Secrets
    version: 0.1.0
    tags: poc,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: This template defines secrets required to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: thoth
    labels:
      app: thoth-core
  stringData:
    app-secret-key: "887a2b06a52fc26cd444344df0276dde756133a2fdf8178c95488fbdc73c69c4"
    thoth-secret: ${THOTH_SECRET}
    ceph-key-id: ${THOTH_CEPH_KEY_ID}
    ceph-secret-key: ${THOTH_CEPH_SECRET_KEY}

parameters:
  - description: Secret to interact with Thoth endpoints that require higher privileges.
    displayName: Thoth secret
    required: true
    name: THOTH_SECRET

  - description: Access key id for Ceph connection.
    displayName: Ceph access key id
    required: true
    name: THOTH_CEPH_KEY_ID

  - description: Secret key for Ceph connection.
    displayName: Ceph secret key
    required: true
    name: THOTH_CEPH_SECRET_KEY
