apiVersion: v1
kind: Template
metadata:
  name: thoth-core
  annotations:
    description: This is Thoth Core - common components 
    openshift.io/display-name: "Thoth Core: common components"
    version: 0.2.0
    tags: poc,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: thoth-core
    app: thoth

objects:

## Service Accounts
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: analyzer
    namespace: ${THOTH_FRONTEND_NAMESPACE}
    labels:
      app: thoth
  automountServiceAccountToken: true

- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: role-jobs-binding
    namespace: ${THOTH_MIDDLETIER_NAMESPACE}
    labels:
      app: thoth
  roleRef:
    kind: ClusterRole
    name: edit
  subjects:
    - kind: ServiceAccount
      name: analyzer
      namespace: ${THOTH_FRONTEND_NAMESPACE}

parameters:
- description: Name of the Thoth Frontend Namespace
  displayName: Thoth Frontend Namespace
  required: true
  name: THOTH_FRONTEND_NAMESPACE

- description: Name of the Thoth Middle Tier Namespace
  displayName: Thoth Middle Tier Namespace
  required: true
  name: THOTH_MIDDLETIER_NAMESPACE

- description: Name of the Thoth Backend Namespace
  displayName: Thoth Backend Namespace
  required: true
  name: THOTH_BACKEND_NAMESPACE
