---
- name: Playbook to provision Thoth Core
  tags:
    - openshift
    - thoth

  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: "check if JanusGraph service exists"
      k8s_raw:
        api_version: v1
        kind: Service
        name: janusgraph
        namespace: "{{ frontend_namespace }}"
      register: janusgraph_service
      ignore_errors: true

    - fail:
        msg: "JanusGraph Service not found, it is required!"
      when: janusgraph_service.failed