---
- name: Playbook to create Thoth ConfigMap and Secret
  tags:
    - openshift
    - thoth

  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: thoth-station.configmaps_and_secrets
      openshift_api_url: "https://paas.upshift.redhat.com"
      THOTH_DEPLOYMENT_NAME: "thoth-stage-core"
      TARGET_NAMESPACE: "thoth-stage-core"
      THOTH_INFRA_NAMESPACE: "thoth-stage-core"
      THOTH_FRONTEND_NAMESPACE: "thoth-stage-core"
      THOTH_MIDDLETIER_NAMESPACE: "thoth-stage-core"
      THOTH_BACKEND_NAMESPACE: "thoth-stage-core"
      THOTH_APP_SECRET_KEY: "secret101"
      THOTH_SECRET: "secret101"
      THOTH_CEPH_SECRET_KEY: "{{ lookup('env','THOTH_CEPH_SECRET_KEY') }}"
      THOTH_CEPH_KEY_ID: "{{ lookup('env','THOTH_CEPH_KEY_ID') }}"
      THOTH_S3_ENDPOINT_URL : "{{ lookup('env','THOTH_S3_ENDPOINT_URL ') }}"
      THOTH_CEPH_BUCKET: "DH-DEV-DATA"
      SENTRY_DSN: "{{ lookup('env','SENTRY_DSN') }}"
      PROMETHEUS_PUSHGATEWAY_HOST: "{{ lookup('env','PROMETHEUS_PUSHGATEWAY_HOST') }}"
      PROMETHEUS_PUSHGATEWAY_PORT: "{{ lookup('env','PROMETHEUS_PUSHGATEWAY_PORT') }}"
      ZUUL_INCOMING_WEBHOOK_SECRET: "{{ lookup('env','ZUUL_INCOMING_WEBHOOK_SECRET') }}"