---
- name: "Playbook to deprovision Thoth Core"
  tags:
    - openshift
    - thoth
    - operations

  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - fail: msg="Bailing out. this play requires 'THOTH_NAMESPACE'"
    when: THOTH_NAMESPACE is not defined

  - name: Deprovision Thoth
    command: "oc delete --namespace={{ THOTH_NAMESPACE }} \
      bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,sa,template,clusterrole --selector 'app=thoth'"

  # We are not deleting the thoth-ops ServiceAccount as we want to keep the token alive!

  - name: Deprovision Amun
    command: "oc delete --namespace={{ THOTH_NAMESPACE }} \
      bc,configmap,cronjob,dc,is,pod,role,rolebinding,route,\
      secret,svc,sa,template,clusterrole --selector 'app=amun'"