---
- name: Playbook to provision Thoth Core
    - openshift
    - thoth

  hosts: localhost
  connection: local
  gather_facts: false

  # vars:
  #   migrated to group_vars/all

  roles:
  - role: thoth-core-imagestreams
  - role: thoth-station.core_templates
    openshift_api_url: "https://paas.upshift.redhat.com"
    namespace: "{{ THOTH_INFRA_NAMESPACE }}"
  - role: thoth-frontend
  - role: thoth-middletier
  - role: thoth-backend
  - role: thoth-infra-buildconfigs
  - role: thoth-jenkins
