---
- name: Playbook to provision Thoth Core
    - openshift
    - thoth

  hosts: localhost
  vars:
    openshift_master_url: "{{ lookup('env','OCP_URL') }}"
    token: "{{ lookup('env','OCP_TOKEN') }}"
    THOTH_BACKEND_NAMESPACE: "goern-dev-thoth"
    THOTH_MIDDLEEND_NAMESPACE: "goern-dev-thoth"
    THOTH_FRONTEND_NAMESPACE: "goern-dev-thoth"
    THOTH_DEPLOYMENT_NAME: "goern-dev-thoth"
    THOTH_CEPH_SECRET_KEY: "{{ lookup('env','THOTH_CEPH_SECRET_KEY') }}"
    THOTH_CEPH_KEY_ID: "{{ lookup('env','THOTH_CEPH_KEY_ID') }}"
    THOTH_CEPH_HOST: "{{ lookup('env','THOTH_CEPH_HOST') }}"
    THOTH_CEPH_BUCKET: "DH-DEV-DATA"
    THOTH_SECRET: "{{ lookup('env','THOTH_SECRET') }}"
    
  gather_facts: false
  connection: local
  roles:
  - role: provision-thoth-core
    playbook_debug: true
