---
- name: Playbook to validate Thoth Core deployment
    - openshift
    - thoth

  hosts: localhost
  vars:
    openshift_master_url: "{{ lookup('env','OCP_URL') }}"
    token: "{{ lookup('env','OCP_TOKEN') }}"
    THOTH_BACKEND_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_MIDDLETIER_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_FRONTEND_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    THOTH_INFRA_NAMESPACE: "{{ lookup('env','USER') }}-thoth-dev"
    
  gather_facts: false
  connection: local
  roles:
  - role: validate-thoth
    playbook_debug: true
